language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-28
    - android-29
jdk:
  - oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;28.0.3"
script:
  - chmod +x gradlew
  - ./gradlew build
  - chmod +x .push.sh
  - ./.push.sh
